### ISSUE TITLE
Assignment 6

### ISSUE THREAD

**Issue by Shorna11** [Shorna11/Assignment-6#1]
Things I have done in this assignment-
1. added a title page
2. created a table of content
3. remodeled the layout
4. added equations
5. after several trials and errors added the references successfully

**Comment by mdscheuerell** [comment]
Hi Shorna. I appreciate your perseverance with this assignment. It looks like you may have had problems with the references because you didn't include this block of code:

```
## load the package
library("knitcitations")

## clean out any existing .bib files
cleanbib()

## set pandoc for formatting
options("citation_format" = "pandoc")
```

as shown [here](https://fish497.github.io/website/lectures/week_07/lec_20_markdown_1.html#knitcitations_package).
